import { NextPage } from "next";
import Head from "next/head";

const Blog: NextPage = () => {
  return (
    <>
      <Head>
        <title>diksi-app</title>
        <meta name='description' content='Generated by Create Next Stack.' />
      </Head>
      <h1>Blog</h1>
    </>
  );
};

export default Blog;
