import { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";

const Blog: NextPage = () => {
  return (
    <>
      <Head>
        <title>diksi-app</title>
        <meta name='description' content='Generated by Create Next Stack.' />
      </Head>
      <section className='mb-40'>
        <Navbar />
        <h1>Blog</h1>
      </section>
    </>
  );
};

export default Blog;
