import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import Navbar from "@/components/Navbar";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>diksi-app</title>
        <meta name='description' content='Generated by Create Next Stack.' />
      </Head>
      <section className='mb-40'>
        <Navbar />
        <div className='bg-neutral-50 px-6 py-24 text-center dark:bg-neutral-900'>
          <h1 className='mb-16 mt-2 text-5xl font-bold tracking-tight md:text-6xl xl:text-7xl'>
            The best offer on the market <br />
            <span className='text-primary'>for your business</span>
          </h1>
          <a
            className='mb-2 mr-2 inline-block rounded bg-blue-500 px-12 pb-3.5 pt-4 text-sm font-medium uppercase leading-normal text-white transition duration-150 ease-in-out hover:bg-blue-800'
            data-te-ripple-init
            data-te-ripple-color='light'
            href='#!'
            role='button'
          >
            Get started
          </a>
          <a
            className='ml-2 inline-block rounded px-12 pb-3.5 pt-4 text-sm font-medium uppercase leading-normal text-blue-600 transition duration-150 ease-in-out hover:bg-blue-800 hover:text-white'
            data-te-ripple-init
            data-te-ripple-color='light'
            href='#!'
            role='button'
          >
            Learn more
          </a>
        </div>
      </section>
    </>
  );
};

export default Index;
